//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilingualSubtitler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class SettingsForAndroid : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsForAndroid defaultInstance = ((SettingsForAndroid)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsForAndroid())));
        
        public static SettingsForAndroid Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".rusPack.srt")]
        public string AndroidSrtPackOrSeparateStreamsFileNameEnding {
            get {
                return ((string)(this["AndroidSrtPackOrSeparateStreamsFileNameEnding"]));
            }
            set {
                this["AndroidSrtPackOrSeparateStreamsFileNameEnding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AndroidCreateSrtPack {
            get {
                return ((bool)(this["AndroidCreateSrtPack"]));
            }
            set {
                this["AndroidCreateSrtPack"] = value;
            }
        }
    }
}
