//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilingualSubtitler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color FirstRussianSubtitlesColor {
            get {
                return ((global::System.Drawing.Color)(this["FirstRussianSubtitlesColor"]));
            }
            set {
                this["FirstRussianSubtitlesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PrimarySubtitlesColor {
            get {
                return ((global::System.Drawing.Color)(this["PrimarySubtitlesColor"]));
            }
            set {
                this["PrimarySubtitlesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SecondarySubsInOneLine {
            get {
                return ((bool)(this["SecondarySubsInOneLine"]));
            }
            set {
                this["SecondarySubsInOneLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveStylesFromSecondarySubs {
            get {
                return ((bool)(this["RemoveStylesFromSecondarySubs"]));
            }
            set {
                this["RemoveStylesFromSecondarySubs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trnsl.1.1.20150627T135643Z.b79b9a9564333355.08ab2bf3ca2a0e1d1bacd63175b724f0ff966" +
            "559\r\n\r\n")]
        public string YandexTranslatorAPIKey {
            get {
                return ((string)(this["YandexTranslatorAPIKey"]));
            }
            set {
                this["YandexTranslatorAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MKVToolNix\\")]
        public string PathToMKVToolnixFolder {
            get {
                return ((string)(this["PathToMKVToolnixFolder"]));
            }
            set {
                this["PathToMKVToolnixFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e:\\Movies\\TempSubs\\")]
        public string PathTempSubs {
            get {
                return ((string)(this["PathTempSubs"]));
            }
            set {
                this["PathTempSubs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public global::System.Drawing.Color SecondRussianSubtitlesColor {
            get {
                return ((global::System.Drawing.Color)(this["SecondRussianSubtitlesColor"]));
            }
            set {
                this["SecondRussianSubtitlesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ThirdRussianSubtitlesColor {
            get {
                return ((global::System.Drawing.Color)(this["ThirdRussianSubtitlesColor"]));
            }
            set {
                this["ThirdRussianSubtitlesColor"] = value;
            }
        }
    }
}
