//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilingualSubtitler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class SubtitlesAppearanceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SubtitlesAppearanceSettings defaultInstance = ((SubtitlesAppearanceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SubtitlesAppearanceSettings())));
        
        public static SubtitlesAppearanceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman;84;20;2;2;0;50;0;0;0;0;0")]
        public string FirstRussianSubtitlesStyleString {
            get {
                return ((string)(this["FirstRussianSubtitlesStyleString"]));
            }
            set {
                this["FirstRussianSubtitlesStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman;189;20;2;2;0;50;0;0;0;0;0")]
        public string SecondRussianSubtitlesStyleString {
            get {
                return ((string)(this["SecondRussianSubtitlesStyleString"]));
            }
            set {
                this["SecondRussianSubtitlesStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman;231;20;2;2;0;50;0;0;0;0;0")]
        public string ThirdRussianSubtitlesStyleString {
            get {
                return ((string)(this["ThirdRussianSubtitlesStyleString"]));
            }
            set {
                this["ThirdRussianSubtitlesStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChangeRussianSubtitlesStylesAccordingToOriginal {
            get {
                return ((bool)(this["ChangeRussianSubtitlesStylesAccordingToOriginal"]));
            }
            set {
                this["ChangeRussianSubtitlesStylesAccordingToOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SecondAndThirdRussianSubtitlesAtTopOfTheScreen {
            get {
                return ((bool)(this["SecondAndThirdRussianSubtitlesAtTopOfTheScreen"]));
            }
            set {
                this["SecondAndThirdRussianSubtitlesAtTopOfTheScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SecondAndThirdRussianSubtitlesAtTopOfTheScreenEnabled {
            get {
                return ((bool)(this["SecondAndThirdRussianSubtitlesAtTopOfTheScreenEnabled"]));
            }
            set {
                this["SecondAndThirdRussianSubtitlesAtTopOfTheScreenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial;42;20;2;2;0;50;0")]
        public string OriginalSubtitlesStyleString {
            get {
                return ((string)(this["OriginalSubtitlesStyleString"]));
            }
            set {
                this["OriginalSubtitlesStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool СhangeOnTheSameDeltaValuesForAllSubtitles {
            get {
                return ((bool)(this["СhangeOnTheSameDeltaValuesForAllSubtitles"]));
            }
            set {
                this["СhangeOnTheSameDeltaValuesForAllSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetTheSameValuesForAllSubtitles {
            get {
                return ((bool)(this["SetTheSameValuesForAllSubtitles"]));
            }
            set {
                this["SetTheSameValuesForAllSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChangeMarginsToPairSubtitles {
            get {
                return ((bool)(this["ChangeMarginsToPairSubtitles"]));
            }
            set {
                this["ChangeMarginsToPairSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MarginCheckBoxChecked {
            get {
                return ((bool)(this["MarginCheckBoxChecked"]));
            }
            set {
                this["MarginCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutlineCheckBoxChecked {
            get {
                return ((bool)(this["OutlineCheckBoxChecked"]));
            }
            set {
                this["OutlineCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SizeCheckBoxChecked {
            get {
                return ((bool)(this["SizeCheckBoxChecked"]));
            }
            set {
                this["SizeCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShadowCheckBoxChecked {
            get {
                return ((bool)(this["ShadowCheckBoxChecked"]));
            }
            set {
                this["ShadowCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransparencyCheckBoxChecked {
            get {
                return ((bool)(this["TransparencyCheckBoxChecked"]));
            }
            set {
                this["TransparencyCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShadowTransparencyCheckBoxChecked {
            get {
                return ((bool)(this["ShadowTransparencyCheckBoxChecked"]));
            }
            set {
                this["ShadowTransparencyCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman;255;20;2;2;0;50;0;0;0;0;0")]
        public string FourthRussianSubtitlesStyleString {
            get {
                return ((string)(this["FourthRussianSubtitlesStyleString"]));
            }
            set {
                this["FourthRussianSubtitlesStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman;0;20;2;2;0;50;0;0;0;0;0")]
        public string FifthRussianSubtitlesStyleString {
            get {
                return ((string)(this["FifthRussianSubtitlesStyleString"]));
            }
            set {
                this["FifthRussianSubtitlesStyleString"] = value;
            }
        }
    }
}
