//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilingualSubtitler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class SubtitlesAppearanceSettingsForAndroid : global::System.Configuration.ApplicationSettingsBase {
        
        private static SubtitlesAppearanceSettingsForAndroid defaultInstance = ((SubtitlesAppearanceSettingsForAndroid)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SubtitlesAppearanceSettingsForAndroid())));
        
        public static SubtitlesAppearanceSettingsForAndroid Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OriginalSubtitlesAndroidStyleString {
            get {
                return ((string)(this["OriginalSubtitlesAndroidStyleString"]));
            }
            set {
                this["OriginalSubtitlesAndroidStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstRussianSubtitlesAndroidStyleString {
            get {
                return ((string)(this["FirstRussianSubtitlesAndroidStyleString"]));
            }
            set {
                this["FirstRussianSubtitlesAndroidStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondRussianSubtitlesAndroidStyleString {
            get {
                return ((string)(this["SecondRussianSubtitlesAndroidStyleString"]));
            }
            set {
                this["SecondRussianSubtitlesAndroidStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdRussianSubtitlesAndroidStyleString {
            get {
                return ((string)(this["ThirdRussianSubtitlesAndroidStyleString"]));
            }
            set {
                this["ThirdRussianSubtitlesAndroidStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthRussianSubtitlesAndroidStyleString {
            get {
                return ((string)(this["FourthRussianSubtitlesAndroidStyleString"]));
            }
            set {
                this["FourthRussianSubtitlesAndroidStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthRussianSubtitlesAndroidStyleString {
            get {
                return ((string)(this["FifthRussianSubtitlesAndroidStyleString"]));
            }
            set {
                this["FifthRussianSubtitlesAndroidStyleString"] = value;
            }
        }
    }
}
